# Auto-generated sheet_localization_key
extends Node

enum sheet_localization_key {
	Laung_Name,
	SigninwithGoogle,
	SigninwithDiscord,
	SigninwithEmail,
	Email,
	UserID,
	Name,
	Openingbrowserforauthentication,
	SignOut,
	bfont_size20Youaresignedinfont_sizeb,
	Username,
	Password,
	Submit,
	Forgotpassword,
	GotoRegister,
	Login,
	Usernameorpasswordisincorrect,
	Usernameisalreadytaken,
	Invalidemailaddress,
	Whatwouldyouliketodo,
	Register,
	Emailaddress,
	GotoLogin,
	Home,
	Changepassword,
	Changeemail,
	Changeidentifier,
	Logout,
	Deleteaccount,
	Verify,
	Currentpassword,
	Newemail,
	Cancel,
	Newidentifier,
	Newpassword,
	Resetpassword,
	Code,
	Verificationcode,
}
